import {StyleSheet} from 'react-native';

export const WarningDetailStyle=StyleSheet.create({
    flex:{
        flex:1
    },
    horVerCenter:{
        alignItems:'center',
        justifyContent:'center'
    },
    topBar:{
        height:50,
        backgroundColor:'#999',
        alignItems:'center',
        justifyContent:'center'
    },
    btnBox:{
        width:29,
        height:50,
        position:'absolute',
        left:10
    },
    backIcon:{
        width:29,
        height:50
    },
    tipContent:{
       height:100,
       flexDirection:'row',
       alignItems:'center',
       justifyContent:'center'
    },
    tipSame:{
       flex:1,
       alignItems:'center',
       justifyContent:'center'
    },
    listBox:{
        flex:1
    },
    itemBox:{
        marginTop:2,
        marginLeft:5,
        marginRight:5,
        marginBottom:2
    },
    btnBoxGO:{
        flexDirection:'row',
        backgroundColor:'#999',
        height:30,
        alignItems:'center',
        justifyContent:'center'
    },
    arrowIcon:{
       position:'absolute',
       right:0,
        width:19,
        height:26
    },
    type:{
        flex:4,
        marginLeft:10
    },
    num:{
        flex:1
    },
    IconLeft:{
        flex:1,
        width:19,
        left:0
    },
    title:{
        borderTopWidth:5,
        borderColor:'#999'
    },
    textTitle:{
        color:'blue',
        fontSize:20,
        textAlign:'center'
    },
    phone:{
        width:40,
        height:40
    },
    phoneBox:{
            position:'absolute',
        right:10,
    }
})