import {StyleSheet} from 'react-native';

export const WatchDirversStyle=StyleSheet.create({
    flex:{
        flex:1
    },
    horVerCenter:{
        alignItems:'center',
        justifyContent:'center'
    },
    topBar:{
        height:50,
        backgroundColor:'#999',
        alignItems:'center',
        justifyContent:'center'
    },
    btnBox:{
        width:29,
        height:50,
        position:'absolute',
        left:10
    },
    backIcon:{
        width:29,
        height:50
    },
    tipText:{
        height:50,
        alignItems:'center',
        justifyContent:'center'
    },
    listBox:{
        flex:1
    },
    itemBox:{
        margin:5
    },
    btnBoxGO:{
        flexDirection:'row',
        margin:10,
        backgroundColor:'#999',
        height:30,
        alignItems:'center',
        justifyContent:'center'
    },
    arrowIcon:{
       position:'absolute',
       right:0,
        width:19,
        height:26
    },
    type:{
        flex:3,
        marginLeft:10
    },
    num:{
        flex:2
    }
})